server:
  port: 0

spring:
  application:
    name: barista-service
  output:
    ansi:
      enabled: ALWAYS
  datasource:
    url: jdbc:mysql://localhost/springbucks
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
  rabbitmq:
    host: localhost
    port: 5672
    username: spring
    password: spring
  cloud:
    stream:
      bindings:
        newOrders:
          group: barista-service
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    sender:
      type: rabbit

order:
  barista-prefix: springbucks-

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"