spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: none
  output:
    ansi:
      enabled: always
  # zookeeper
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

info:
  app:
    author: DigitalSonic
    encoding: @project.build.sourceEncoding@

server:
  port: 0