spring:
  output:
    ansi:
      enabled: always
# consul
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        prefer-ip-address: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
server:
  port: 0