spring:
  output:
    ansi:
      enabled: always
  datasource:
    url: jdbc:h2:mem:foo
    username: sa
    password: n/z7PyA5cvcXvs8px8FVmBVpaRyNsvJb3X7YfS38DJrIg25EbZaZGvH4aHcnc97Om0islpCAPc3MqsGvsrxVJw==
    druid:
#      initial-size: 5
      initial-size: 2
      max-active: 5
#      min-idle: 5
      min-idle: 2
      connect-properties: config.decrypt=true;config.decrypt.key=${public-key}
      filter:
        config:
          enabled: true
        stat:
          enabled: true
          log-slow-sql: true
          slow-sql-millis: 100

      #      filters: conn,config,stat,slf4j
      filters: config,slf4j
      test-on-borrow: true
      test-on-return: true
      test-while-idle: true

public-key: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBALS8ng1XvgHrdOgm4pxrnUdt3sXtu/E8My9KzX8sXlz+mXRZQCop7NVQLne25pXHtZoDYuMh3bzoGj6v5HvvAQ8CAwEAAQ==

management:
  endpoints:
    web:
      exposure:
        include: "*"