spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: none
  output:
    ansi:
      enabled: always
  thymeleaf:
    cache: false

management:
  endpoints:
    web:
      exposure:
        include: "*"