spring:
  output:
    ansi:
      enabled: always
management:
  endpoints:
    web:
      exposure:
        include: "*"
server:
  port: 0

feign:
  client:
    config:
      default:
        connect-timeout: 500
        read-timeout: 500